# Use before Cloudflare Origin Certificate is installed.
# sudo cp deploy/nginx/improvpl-http-only.conf /etc/nginx/sites-available/improvpl

server {
    listen 80;
    server_name improv.pl www.improv.pl;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/improvuser/improvpl/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/improvuser/improvpl/improvpl.sock;
    }
}