server {
    listen 80;
    server_name improv.pl www.improv.pl;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name improv.pl www.improv.pl;

    ssl_certificate     /etc/ssl/cloudflare/improv.pl.pem;
    ssl_certificate_key /etc/ssl/cloudflare/improv.pl.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/improvuser/improvpl/staticfiles/;
    }

    location /media/ {
        alias /home/improvuser/improvpl/media/;
    }

    location / {
        include proxy_params;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/home/improvuser/improvpl/improvpl.sock;
    }
}